### ISSUE TITLE
oai-spgwu missing in docker-compose-basic-nrf.yaml

### ISSUE THREAD

**Issue by mackskaren** [Anass-23/5G-Network#7]
When trying to adjust the mcc and mnc values in the docker yaml file, the oai-spgwu service is missing. should I manually add the service as:
oai-spgwu:
    environment:
        -MCC=MCC
        -MNC=MNC

is there anything else that I would need to add or would this be it? or were some changes made in the background and it is no longer needed?

**Comment by mackskaren** [comment]
fixed the problem. in the most recent branch for https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed.git, it runs v2.0.1 i think which moved on from oai-spgwu and moved it to oai-upf. to use oai-spgwu, run `git checkout -f v1.5.x (0 or 1)` to get the branch with oai-spgwu. you also don't need to pull the docker images manually, as running `python3 core-network.py --type start-basic --scenario 1` to start the CN will pull the images if they haven't been pulled yet, though if you manually pull, pull with tag v1.5.x instead of develop.

**Comment by Anass-23** [comment]
Hi there!

Apologies for the delayed response. I wanted to let you know that this project was developed about a year ago. Unfortunately, I haven't had access to the lab equipment or been able to maintain and update the information, fix bugs, or test the setup manual since then.

I'm glad you have been able to fix the problem so others that find this manual helpful are also able to fight with these types of issues.
